name: Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_DEPLOY_KEY }}

    # - name: Test SSH connection
      # run: ssh -v -o StrictHostKeyChecking=no -p 8647 ${{ secrets.VPS_HOST }} 'echo "SSH connection successful"'

    # - name: Sync files to VPS
      # run: rsync -avz --delete-after --verbose -e "ssh -p 8647 -o StrictHostKeyChecking=no" --exclude='.git' --exclude='node_modules' --exclude='vendor' --exclude='.env' ./ ${{ secrets.VPS_HOST }}:/home/juvhost1/api-sport-reserve.juvhost.com

    - name: Run deployment script on VPS
      run: ssh -o StrictHostKeyChecking=no -p 8647 ${{ secrets.VPS_HOST }} 'bash -s' < deploy.sh
